# Jenkins Shared Library Configuration

SLACK_CHANNEL_NAME=build-status
ENVIRONMENT=prod

CODE_BASE_PATH=env/prod

ACTION_MESSAGE=Deployment started successfully

KEEP_APPROVAL_STAGE=true

# Git Configuration
GIT_URL=https://github.com/Rawatsandeep001/ansible-shared-library.git
BRANCH=main

# Ansible Configuration
PLAYBOOK=site.yml
INVENTORY=inventory/prod
